### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by sawyerzhu** [redis/redis-rb#659]
When using SSL to rpush long string, it will throw this exception. The version is 3.3.1.

OpenSSL::SSL::SSLErrorWaitWritable: write would block>, :backtrace=>["org/jruby/ext/openssl/SSLSocket.java:672:in `syswrite_nonblock'"

**Comment by badboy** [comment]
This was fixed in 3.3.2 (see https://github.com/redis/redis-rb/pull/644), but that version introduced another regression (4.0 is on its way with a proper fix)

**Comment by sawyerzhu** [comment]
With version 4.0.0.rc1, The error is still exists. This is the exception emssage

exception=>#<IOError: Broken pipe>, :backtrace=>["org/jruby/ext/openssl/SSLSocket.java:672:in `syswrite_nonblock'"

**Comment by sawyerzhu** [comment]
The Ruby version is jruby-complete-1.7.11.jar

**Comment by sawyerzhu** [comment]
It seems error(IOError:Broken pipe) caused by our local network environment. And with version 4.0.0-rc1 the issue gone.  Thanks @badboy
